### ISSUE TITLE
[UI] 이메일 로그인 -> 비밀번호 재설정 -> 뒤로가기 클릭시 화면 이동 오류

### ISSUE THREAD

**Issue by shieldnet** [cau-deal/deal-application#3]
### 이메일 로그인 -> 비밀번호 재설정 -> 뒤로가기 클릭시 화면 이동 오류
 * 이메일 로그인 클릭하고, 비밀번호 재설정 누른 후  ' < ' 버튼을 누르면 메인 로그인 방법 선택창으로 이동하는 것 같은데. 혹시 의도한건지 궁금해용
 * 혹시 다시 이메일 입력하는 창으로 가는게 자연스럽지 않을까 해서 남겨봅니다

**Comment by leesnhyun** [comment]
Done.

Sorry for my mistake :)
(Also, I will update prototype UI mockup. )
